"""Generate the canonical work-item library (work_items.json).

Every norm value is planning-grade and carries a source label (norm_basis). Anchors
follow the guide values in EXECUTION_PLAN.md §4.1: Butler, *Guide to Ship Repair
Estimates* (2012) for labour-hour norms, and a composite of published yard tariffs
(2019-2024) for money rates. These are guide norms for leveling deltas — NOT yard
tariffs. Run: `python -m app.seed.build_work_items` (writes work_items.json alongside).
"""
from __future__ import annotations

import json
from pathlib import Path

BUTLER = "guide: Butler, Guide to Ship Repair Estimates (2012)"
TARIFF = "guide: composite of published yard tariffs 2019-2024"

# Each row: (code, title, uom, norm_value, norm_unit, norm_basis, factors, typical)
SECTIONS: dict[int, tuple[str, str, list[tuple]]] = {
    1: ("GS", "General Services", [
        ("GS-001", "Dockage / general dry-dock hire per day", "day", 14000, "USD/day",
         TARIFF, {"MR": 11000, "Aframax": 15000, "LR2": 16000, "VLCC": 26000}, True),
        ("GS-002", "Wharfage / berth alongside per day", "day", 3200, "USD/day", TARIFF, {}, True),
        ("GS-003", "Docking and undocking operation (lump)", "lot", 130000, "USD", TARIFF,
         {"MR": 90000, "Aframax": 130000, "LR2": 140000, "VLCC": 210000}, True),
        ("GS-004", "Keel and side blocks — arrange to docking plan", "lot", 12, "mh/block",
         BUTLER, {"note": "5-20 mh/block scaling with DWT"}, True),
        ("GS-005", "Fire watch / hot-work standby per shift", "shift", 220, "USD/shift", TARIFF, {}, True),
        ("GS-006", "Gas-free inspection and certificate", "ea", 4500, "USD", TARIFF, {}, True),
        ("GS-007", "Shore power supply per kWh", "kWh", 0.25, "USD/kWh", TARIFF, {}, True),
        ("GS-008", "Cooling / circulating water supply per day", "day", 900, "USD/day", TARIFF, {}, False),
        ("GS-009", "Fresh water supply per tonne", "t", 9, "USD/t", TARIFF, {}, True),
        ("GS-010", "Garbage removal / skip per day", "day", 180, "USD/day", TARIFF, {}, True),
        ("GS-011", "Sludge / slop disposal per m3", "m3", 85, "USD/m3", TARIFF, {}, True),
        ("GS-012", "Bilge water disposal per m3", "m3", 70, "USD/m3", TARIFF, {}, False),
        ("GS-013", "Mobile crane 25 t per hour", "hr", 300, "USD/hr", TARIFF, {}, True),
        ("GS-014", "Mobile crane 60 t per hour", "hr", 520, "USD/hr", TARIFF, {}, True),
        ("GS-015", "Forklift with driver per hour", "hr", 65, "USD/hr", TARIFF, {}, True),
        ("GS-016", "Staging — erect and dismantle per m3", "m3", 18, "USD/m3", TARIFF, {}, True),
        ("GS-017", "Transport within yard per day", "day", 240, "USD/day", TARIFF, {}, False),
        ("GS-018", "Ballast water handling / de-ballast per day", "day", 650, "USD/day", TARIFF, {}, False),
        ("GS-019", "Tank ventilation / blowers per day", "day", 140, "USD/day", TARIFF, {}, True),
        ("GS-020", "Watchman / security per shift", "shift", 130, "USD/shift", TARIFF, {}, True),
        ("GS-021", "Environmental / effluent levy (lump)", "lot", 3500, "USD", TARIFF, {}, False),
        ("GS-022", "Hot-work permit administration per permit", "ea", 120, "USD", TARIFF, {}, False),
        ("GS-023", "Riding-crew berths / messing per day", "day", 55, "USD/day", TARIFF, {}, False),
        ("GS-024", "Agency, port and security services (lump)", "lot", 8500, "USD", TARIFF, {}, True),
        ("GS-025", "Compressed air supply per day", "day", 320, "USD/day", TARIFF, {}, False),
        ("GS-026", "Scaffold / cherry-picker access unit per day", "day", 420, "USD/day", TARIFF, {}, False),
    ]),
    2: ("HT", "Hull Treatment & Painting", [
        ("HT-001", "HP fresh-water wash per m2", "m2", 2.0, "USD/m2", TARIFF, {"band": [1.5, 2.5]}, True),
        ("HT-002", "Spot blast Sa 2.0 per m2", "m2", 11, "USD/m2", TARIFF, {"band": [9, 14]}, True),
        ("HT-003", "Full blast Sa 2.5 per m2", "m2", 23, "USD/m2", TARIFF, {"band": [18, 28]}, True),
        ("HT-004", "Sweep blast per m2", "m2", 7, "USD/m2", TARIFF, {}, True),
        ("HT-005", "Power-tool cleaning St 3 per m2", "m2", 6, "USD/m2", TARIFF, {}, True),
        ("HT-006", "High-pressure UHP water-jetting per m2", "m2", 9, "USD/m2", TARIFF, {}, False),
        ("HT-007", "Anti-corrosive coat application per m2 (per coat)", "m2", 4.5, "USD/m2", TARIFF,
         {"band": [3, 6]}, True),
        ("HT-008", "Anti-fouling coat application per m2 (per coat)", "m2", 5.0, "USD/m2", TARIFF, {}, True),
        ("HT-009", "Boot-top coating per m2 (per coat)", "m2", 5.5, "USD/m2", TARIFF, {}, True),
        ("HT-010", "Topside / freeboard coating per m2 (per coat)", "m2", 5.0, "USD/m2", TARIFF, {}, True),
        ("HT-011", "Deck non-skid coating per m2", "m2", 12, "USD/m2", TARIFF, {}, False),
        ("HT-012", "Draft marks / plimsoll re-mark and paint (lump)", "lot", 2600, "USD", TARIFF, {}, True),
        ("HT-013", "Ship name and port of registry re-mark (lump)", "lot", 1800, "USD", TARIFF, {}, False),
        ("HT-014", "Hull anodes — supply and weld per kg", "kg", 9, "USD/kg", TARIFF, {}, True),
        ("HT-015", "Hull anodes — fit only per piece", "ea", 26, "USD/ea", BUTLER, {}, True),
        ("HT-016", "Sea-chest grid coating per m2", "m2", 28, "USD/m2", TARIFF, {}, False),
        ("HT-017", "Cargo / ballast tank coating per m2", "m2", 16, "USD/m2", TARIFF, {}, True),
        ("HT-018", "Cofferdam / void coating per m2", "m2", 15, "USD/m2", TARIFF, {}, False),
        ("HT-019", "Stripe coat by brush at edges per m", "m", 1.2, "USD/m", TARIFF, {}, False),
        ("HT-020", "Paint dry-film-thickness inspection (lump)", "lot", 1400, "USD", TARIFF, {}, False),
        ("HT-021", "Masking and protection of fittings (lump)", "lot", 2200, "USD", TARIFF, {}, True),
        ("HT-022", "Rudder and skeg coating per m2", "m2", 24, "USD/m2", TARIFF, {}, False),
        ("HT-023", "Bilge keel — grit blast and coat per m2", "m2", 26, "USD/m2", TARIFF, {}, False),
        ("HT-024", "Propeller boss / cone coating (lump)", "lot", 1200, "USD", TARIFF, {}, False),
    ]),
    3: ("ST", "Steel Renewals", [
        ("ST-001", "Shell plate renewal <= 12.5 mm per tonne", "t", 230, "mh/t", BUTLER,
         {"band": [200, 250], "curvature_single": 1.2, "curvature_double": 1.3,
          "loc_tanktop": 1.0, "loc_wing": 1.15, "loc_underdeck": 1.25,
          "consumables_usd_t": 220,
          "all_in_usd_t": {"ISC": 2900, "China": 2900, "Med": 3900, "SEA": 4250, "NEur": 7500}}, True),
        ("ST-002", "Shell plate renewal <= 15 mm per tonne", "t", 235, "mh/t", BUTLER, {"band": [205, 255]}, True),
        ("ST-003", "Shell plate renewal <= 20 mm per tonne", "t", 245, "mh/t", BUTLER, {"band": [215, 270]}, True),
        ("ST-004", "Internal members (frames/brackets/stiffeners) per tonne", "t", 285, "mh/t", BUTLER,
         {"band": [250, 320]}, True),
        ("ST-005", "Deck plate renewal per tonne", "t", 240, "mh/t", BUTLER, {}, True),
        ("ST-006", "Wing-tank internals per tonne (location factor)", "t", 330, "mh/t", BUTLER,
         {"loc_factor": 1.15}, True),
        ("ST-007", "Double-bottom internals per tonne", "t", 320, "mh/t", BUTLER, {"loc_factor": 1.15}, True),
        ("ST-008", "Under-deck structure per tonne (location factor)", "t", 345, "mh/t", BUTLER,
         {"loc_factor": 1.25}, True),
        ("ST-009", "Pipe tunnel / duct keel steel per tonne", "t", 360, "mh/t", BUTLER, {}, False),
        ("ST-010", "Insert plate <= 0.25 m2 per piece", "ea", 14, "mh/ea", BUTLER, {}, True),
        ("ST-011", "Insert plate 0.25-1.0 m2 per piece", "ea", 26, "mh/ea", BUTLER, {}, True),
        ("ST-012", "Doubler plate (temporary) per piece", "ea", 18, "mh/ea", BUTLER, {}, False),
        ("ST-013", "Crop and renew bulwark per metre", "m", 6, "mh/m", BUTLER, {}, False),
        ("ST-014", "Face plate / flat bar renewal per metre", "m", 5, "mh/m", BUTLER, {}, False),
        ("ST-015", "NDT ultrasonic thickness spot per point", "point", 22, "USD/point", TARIFF, {}, True),
        ("ST-016", "NDT MPI / dye-penetrant per weld", "ea", 45, "USD/ea", TARIFF, {}, True),
        ("ST-017", "Class surveyor steel attendance per visit", "ea", 850, "USD/visit", TARIFF, {}, True),
        ("ST-018", "Staging for steelwork in tanks per m3", "m3", 22, "USD/m3", TARIFF, {}, True),
    ]),
    4: ("SV", "Sea Valves & Overboards", [
        ("SV-001", "Overhaul gate valve DN80-DN150 per valve", "ea", 22, "mh/ea", BUTLER, {}, True),
        ("SV-002", "Overhaul gate valve DN200-DN400 per valve", "ea", 38, "mh/ea", BUTLER, {}, True),
        ("SV-003", "Overhaul globe valve DN80-DN200 per valve", "ea", 20, "mh/ea", BUTLER, {}, True),
        ("SV-004", "Overhaul butterfly valve per valve", "ea", 16, "mh/ea", BUTLER, {}, True),
        ("SV-005", "Sea chest clean and coat per chest", "ea", 1400, "USD/ea", TARIFF, {}, True),
        ("SV-006", "Sea chest grid — remove, clean, refit per grid", "ea", 620, "USD/ea", TARIFF, {}, True),
        ("SV-007", "Sea chest anodes — renew per set", "set", 480, "USD/set", TARIFF, {}, True),
        ("SV-008", "Overboard valve pressure test per valve", "ea", 6, "mh/ea", BUTLER, {}, True),
        ("SV-009", "Ship-side valve blank / spade for test per piece", "ea", 4, "mh/ea", BUTLER, {}, False),
        ("SV-010", "Renew valve studs / gaskets per valve", "ea", 8, "mh/ea", BUTLER, {}, True),
        ("SV-011", "Overhaul non-return / storm valve per valve", "ea", 14, "mh/ea", BUTLER, {}, False),
        ("SV-012", "Bell-mouth / suction rose clean per unit", "ea", 5, "mh/ea", BUTLER, {}, False),
    ]),
    5: ("PR", "Propulsion & Tail Shaft", [
        ("PR-001", "Tail shaft withdraw and survey — keyless (lump)", "lot", 460, "mh", BUTLER,
         {"band": [380, 550]}, True),
        ("PR-002", "Tail shaft withdraw and survey — keyed (lump)", "lot", 520, "mh", BUTLER, {}, False),
        ("PR-003", "Stern-tube seal overhaul — aft per set", "set", 140, "mh/set", BUTLER, {}, True),
        ("PR-004", "Stern-tube seal overhaul — forward per set", "set", 120, "mh/set", BUTLER, {}, True),
        ("PR-005", "Propeller polish grade A per blade", "blade", 6, "mh/blade", BUTLER, {}, True),
        ("PR-006", "Propeller polish grade B per blade", "blade", 4, "mh/blade", BUTLER, {}, True),
        ("PR-007", "Propeller polish grade C per blade", "blade", 3, "mh/blade", BUTLER, {}, False),
        ("PR-008", "Propeller removal and refit (lump)", "lot", 180, "mh", BUTLER, {}, True),
        ("PR-009", "Propeller pitch / static balance check (lump)", "lot", 40, "mh", BUTLER, {}, False),
        ("PR-010", "Rope guard — remove, repair, refit (lump)", "lot", 55, "mh", BUTLER, {}, True),
        ("PR-011", "Stern-tube oil sample and analysis per sample", "ea", 240, "USD/ea", TARIFF, {}, True),
        ("PR-012", "Rudder — bearing clearances (jumping/wear-down)", "lot", 60, "mh", BUTLER, {}, True),
        ("PR-013", "Rudder — drop test and pintle survey (lump)", "lot", 120, "mh", BUTLER, {}, True),
        ("PR-014", "Bow thruster — inspect and grease (lump)", "lot", 45, "mh", BUTLER, {}, True),
        ("PR-015", "Bow thruster — blade / seal overhaul (lump)", "lot", 220, "mh", BUTLER, {}, False),
        ("PR-016", "Shaft coupling bolts — inspect / renew per set", "set", 35, "mh/set", BUTLER, {}, False),
    ]),
    6: ("BE", "Boiler & Economizer", [
        ("BE-001", "Boiler retube per tube", "tube", 3.5, "mh/tube", BUTLER, {}, True),
        ("BE-002", "Economizer retube per tube", "tube", 4.0, "mh/tube", BUTLER, {}, True),
        ("BE-003", "Boiler casing steel renewal per tonne", "t", 320, "mh/t", BUTLER, {}, False),
        ("BE-004", "Refractory / brickwork renewal per m2", "m2", 240, "USD/m2", TARIFF, {}, True),
        ("BE-005", "Safety valve overhaul and float-set per valve", "ea", 18, "mh/ea", BUTLER, {}, True),
        ("BE-006", "Burner overhaul per burner", "ea", 22, "mh/ea", BUTLER, {}, True),
        ("BE-007", "Boiler hydraulic test (lump)", "lot", 24, "mh", BUTLER, {}, True),
        ("BE-008", "Gauge glass / mounting renewal per set", "set", 6, "mh/set", BUTLER, {}, False),
        ("BE-009", "Economizer soot / water wash (lump)", "lot", 30, "mh", BUTLER, {}, False),
        ("BE-010", "Boiler internal survey attendance (lump)", "lot", 12, "mh", BUTLER, {}, True),
    ]),
    7: ("PI", "Piping & Tanks", [
        ("PI-001", "Steel pipe renewal per inch-metre", "in-m", 4.5, "mh/in-m", BUTLER, {}, True),
        ("PI-002", "Cu-Ni pipe renewal per inch-metre", "in-m", 6.0, "mh/in-m", BUTLER, {}, True),
        ("PI-003", "GRE / GRP pipe renewal per inch-metre", "in-m", 5.0, "mh/in-m", BUTLER, {}, False),
        ("PI-004", "Ballast tank clean for hot work per m3", "m3", 6, "USD/m3", TARIFF, {}, True),
        ("PI-005", "Cargo (oil) tank clean for hot work per m3", "m3", 14, "USD/m3", TARIFF,
         {"note": "grade-dependent; disputes common"}, True),
        ("PI-006", "Slop tank clean and dispose per m3", "m3", 22, "USD/m3", TARIFF, {}, True),
        ("PI-007", "Bunker tank clean for hot work per m3", "m3", 18, "USD/m3", TARIFF, {}, True),
        ("PI-008", "Cargo tank steaming / mucking (lump)", "lot", 4200, "USD", TARIFF, {}, False),
        ("PI-009", "IGS deck seal — overhaul (lump)", "lot", 40, "mh", BUTLER, {}, False),
        ("PI-010", "IGS scrubber internal inspection (lump)", "lot", 30, "mh", BUTLER, {}, False),
        ("PI-011", "Valve DN80-DN150 renew in line per valve", "ea", 10, "mh/ea", BUTLER, {}, True),
        ("PI-012", "Valve DN200-DN400 renew in line per valve", "ea", 18, "mh/ea", BUTLER, {}, True),
        ("PI-013", "Hydraulic line renewal per metre", "m", 2.5, "mh/m", BUTLER, {}, False),
        ("PI-014", "Air / sounding pipe renewal per piece", "ea", 5, "mh/ea", BUTLER, {}, True),
        ("PI-015", "Pipe support / clamp renewal per piece", "ea", 3, "mh/ea", BUTLER, {}, False),
        ("PI-016", "Tank pressure / vacuum test per tank", "ea", 8, "mh/ea", BUTLER, {}, True),
        ("PI-017", "Mud box / strainer clean per unit", "ea", 4, "mh/ea", BUTLER, {}, True),
        ("PI-018", "Cargo heating coil — pressure test per tank", "ea", 12, "mh/ea", BUTLER, {}, False),
        ("PI-019", "Ballast line flushing (lump)", "lot", 26, "mh", BUTLER, {}, False),
        ("PI-020", "Save-all / scupper pipe renewal per piece", "ea", 4, "mh/ea", BUTLER, {}, False),
    ]),
    8: ("MC", "Machinery Overhauls", [
        ("MC-001", "Main engine unit overhaul per cylinder", "cyl", 120, "mh/cyl", BUTLER, {}, True),
        ("MC-002", "Auxiliary engine overhaul per cylinder", "cyl", 40, "mh/cyl", BUTLER, {}, True),
        ("MC-003", "ME turbocharger overhaul per unit", "ea", 90, "mh/ea", BUTLER, {}, True),
        ("MC-004", "Fuel-oil cooler retube / clean per unit", "ea", 34, "mh/ea", BUTLER, {}, True),
        ("MC-005", "Lube-oil cooler retube / clean per unit", "ea", 34, "mh/ea", BUTLER, {}, True),
        ("MC-006", "Central cooler plate-stack clean per unit", "ea", 28, "mh/ea", BUTLER, {}, True),
        ("MC-007", "Centrifugal pump overhaul per unit", "ea", 20, "mh/ea", BUTLER, {}, True),
        ("MC-008", "Screw / gear pump overhaul per unit", "ea", 24, "mh/ea", BUTLER, {}, True),
        ("MC-009", "Oily-water separator overhaul (lump)", "lot", 30, "mh", BUTLER, {}, False),
        ("MC-010", "Purifier overhaul per unit", "ea", 26, "mh/ea", BUTLER, {}, True),
        ("MC-011", "Air compressor overhaul per unit", "ea", 32, "mh/ea", BUTLER, {}, True),
        ("MC-012", "Windlass overhaul (lump)", "lot", 60, "mh", BUTLER, {}, True),
        ("MC-013", "Mooring winch overhaul per unit", "ea", 45, "mh/ea", BUTLER, {}, True),
        ("MC-014", "Steering gear overhaul (lump)", "lot", 70, "mh", BUTLER, {}, True),
        ("MC-015", "Deck crane / provision crane overhaul per unit", "ea", 55, "mh/ea", BUTLER, {}, False),
        ("MC-016", "Crane wire renewal per metre", "m", 0.6, "mh/m", BUTLER, {}, True),
        ("MC-017", "Anchor chain calibration and gauging (lump)", "lot", 40, "mh", BUTLER, {}, True),
        ("MC-018", "Heat exchanger pressure test per unit", "ea", 8, "mh/ea", BUTLER, {}, True),
        ("MC-019", "Fresh-water generator overhaul (lump)", "lot", 34, "mh", BUTLER, {}, False),
        ("MC-020", "Incinerator overhaul (lump)", "lot", 28, "mh", BUTLER, {}, False),
        ("MC-021", "Provision / AC refrigeration compressor overhaul per unit", "ea", 30, "mh/ea", BUTLER, {}, False),
        ("MC-022", "Ballast water treatment system service (lump)", "lot", 48, "mh", BUTLER, {}, True),
    ]),
    9: ("EL", "Electrical & Automation", [
        ("EL-001", "Motor overhaul <= 15 kW per unit", "ea", 12, "mh/ea", BUTLER, {}, True),
        ("EL-002", "Motor overhaul 15-75 kW per unit", "ea", 22, "mh/ea", BUTLER, {}, True),
        ("EL-003", "Motor overhaul > 75 kW per unit", "ea", 40, "mh/ea", BUTLER, {}, True),
        ("EL-004", "Main switchboard maintenance (lump)", "lot", 45, "mh", BUTLER, {}, True),
        ("EL-005", "Megger / insulation-resistance survey (lump)", "lot", 30, "mh", BUTLER, {}, True),
        ("EL-006", "Alarm / monitoring point test per point", "point", 0.5, "mh/point", BUTLER, {}, True),
        ("EL-007", "ICCP system — anodes and reference cells (lump)", "lot", 60, "mh", BUTLER, {}, True),
        ("EL-008", "MGPS (marine growth prevention) service (lump)", "lot", 24, "mh", BUTLER, {}, False),
        ("EL-009", "Battery bank renewal per set", "set", 18, "mh/set", BUTLER, {}, True),
        ("EL-010", "Navigation-light panel test and repair (lump)", "lot", 10, "mh", BUTLER, {}, True),
        ("EL-011", "Emergency generator test and service (lump)", "lot", 26, "mh", BUTLER, {}, True),
        ("EL-012", "EGCS (scrubber) sensor / analyser service (lump)", "lot", 40, "mh", BUTLER, {}, False),
        ("EL-013", "BWTS sensor / UV-lamp service (lump)", "lot", 34, "mh", BUTLER, {}, True),
        ("EL-014", "Shaft earthing / slip-ring service (lump)", "lot", 8, "mh", BUTLER, {}, False),
        ("EL-015", "Shore-connection (cold-ironing) panel test (lump)", "lot", 20, "mh", BUTLER, {}, False),
        ("EL-016", "Automation / IAS card and I/O test (lump)", "lot", 30, "mh", BUTLER, {}, False),
    ]),
    10: ("CS", "Class, Surveys & Owner's Items", [
        ("CS-001", "Special survey hull attendance (lump)", "lot", 12000, "USD", TARIFF, {}, True),
        ("CS-002", "Tail-shaft survey attendance (lump)", "lot", 3800, "USD", TARIFF, {}, True),
        ("CS-003", "UWILD in lieu of docking — diver survey (note)", "lot", 9000, "USD", TARIFF,
         {"note": "alternative to docking where class permits"}, True),
        ("CS-004", "Load-line item survey (lump)", "lot", 2600, "USD", TARIFF, {}, True),
        ("CS-005", "MLC / accommodation inspection (lump)", "lot", 1800, "USD", TARIFF, {}, False),
        ("CS-006", "Anchor and chain ranging + gauging per shackle", "shackle", 240, "USD/shackle", TARIFF, {}, True),
        ("CS-007", "Anchor / chain re-marking and painting (lump)", "lot", 1400, "USD", TARIFF, {}, False),
        ("CS-008", "Liferaft service and re-certification per raft", "ea", 620, "USD/ea", TARIFF, {}, True),
        ("CS-009", "Gangway / accommodation ladder load test (lump)", "lot", 900, "USD", TARIFF, {}, True),
        ("CS-010", "Lifeboat / davit 5-year load test (lump)", "lot", 3200, "USD", TARIFF, {}, True),
        ("CS-011", "Fixed CO2 / firefighting system service (lump)", "lot", 4200, "USD", TARIFF, {}, True),
        ("CS-012", "Miscellaneous owner's works allowance (lump)", "lot", 15000, "USD", TARIFF,
         {"note": "owner-directed contingency"}, True),
    ]),
}


def build() -> list[dict]:
    items: list[dict] = []
    for section, (_prefix, section_name, rows) in SECTIONS.items():
        for code, title, uom, norm_value, norm_unit, basis, factors, typical in rows:
            items.append({
                "code": code,
                "section": section,
                "section_name": section_name,
                "title": title,
                "uom": uom,
                "norm_value": norm_value,
                "norm_unit": norm_unit,
                "norm_basis": basis,
                "factors": factors,
                "typical": typical,
            })
    return items


if __name__ == "__main__":
    data = build()
    out = Path(__file__).with_name("work_items.json")
    out.write_text(json.dumps(data, indent=2))
    # sanity: every item carries a norm_basis
    assert all(i["norm_basis"] for i in data), "some items missing norm_basis"
    print(f"wrote {len(data)} work items -> {out}")
